bmpblock: 1.2

compression: 2

images:

  # We must specify a font blob to use to render the HWID
  $HWID:              hwid_fonts.bin

  # This URL never changes
  url:               Url.bmp

  # The background images are from the UI people
  devmode_bg:        Devmode_aio.bmp
  remove_bg:         Remove_aio.bmp
  yuck_bg:           Yuck_aio.bmp
  insert_bg:         Insert_aio.bmp

  # The following strings must be approved by the localization people
  en_model_text:       ./localized_images/en/model.bmp
  en_devmode_text:     ./localized_images/en/devmode.bmp
  en_remove_text:      ./localized_images/en/remove.bmp
  en_yuck_text:        ./localized_images/en/yuck.bmp
  en_insert_text:      ./localized_images/en/insert.bmp

  es_419_model_text:       ./localized_images/es_419/model.bmp
  es_419_devmode_text:     ./localized_images/es_419/devmode.bmp
  es_419_remove_text:      ./localized_images/es_419/remove.bmp
  es_419_yuck_text:        ./localized_images/es_419/yuck.bmp
  es_419_insert_text:      ./localized_images/es_419/insert.bmp

  pt_BR_model_text:       ./localized_images/pt_BR/model.bmp
  pt_BR_devmode_text:     ./localized_images/pt_BR/devmode.bmp
  pt_BR_remove_text:      ./localized_images/pt_BR/remove.bmp
  pt_BR_yuck_text:        ./localized_images/pt_BR/yuck.bmp
  pt_BR_insert_text:      ./localized_images/pt_BR/insert.bmp

  en_GB_model_text:       ./localized_images/en_GB/model.bmp
  en_GB_devmode_text:     ./localized_images/en_GB/devmode.bmp
  en_GB_remove_text:      ./localized_images/en_GB/remove.bmp
  en_GB_yuck_text:        ./localized_images/en_GB/yuck.bmp
  en_GB_insert_text:      ./localized_images/en_GB/insert.bmp

  fr_model_text:       ./localized_images/fr/model.bmp
  fr_devmode_text:     ./localized_images/fr/devmode.bmp
  fr_remove_text:      ./localized_images/fr/remove.bmp
  fr_yuck_text:        ./localized_images/fr/yuck.bmp
  fr_insert_text:      ./localized_images/fr/insert.bmp

  es_model_text:       ./localized_images/es/model.bmp
  es_devmode_text:     ./localized_images/es/devmode.bmp
  es_remove_text:      ./localized_images/es/remove.bmp
  es_yuck_text:        ./localized_images/es/yuck.bmp
  es_insert_text:      ./localized_images/es/insert.bmp

  pt_PT_model_text:       ./localized_images/pt_PT/model.bmp
  pt_PT_devmode_text:     ./localized_images/pt_PT/devmode.bmp
  pt_PT_remove_text:      ./localized_images/pt_PT/remove.bmp
  pt_PT_yuck_text:        ./localized_images/pt_PT/yuck.bmp
  pt_PT_insert_text:      ./localized_images/pt_PT/insert.bmp

  ca_model_text:       ./localized_images/ca/model.bmp
  ca_devmode_text:     ./localized_images/ca/devmode.bmp
  ca_remove_text:      ./localized_images/ca/remove.bmp
  ca_yuck_text:        ./localized_images/ca/yuck.bmp
  ca_insert_text:      ./localized_images/ca/insert.bmp

  it_model_text:       ./localized_images/it/model.bmp
  it_devmode_text:     ./localized_images/it/devmode.bmp
  it_remove_text:      ./localized_images/it/remove.bmp
  it_yuck_text:        ./localized_images/it/yuck.bmp
  it_insert_text:      ./localized_images/it/insert.bmp

  de_model_text:       ./localized_images/de/model.bmp
  de_devmode_text:     ./localized_images/de/devmode.bmp
  de_remove_text:      ./localized_images/de/remove.bmp
  de_yuck_text:        ./localized_images/de/yuck.bmp
  de_insert_text:      ./localized_images/de/insert.bmp

  el_model_text:       ./localized_images/el/model.bmp
  el_devmode_text:     ./localized_images/el/devmode.bmp
  el_remove_text:      ./localized_images/el/remove.bmp
  el_yuck_text:        ./localized_images/el/yuck.bmp
  el_insert_text:      ./localized_images/el/insert.bmp

  nl_model_text:       ./localized_images/nl/model.bmp
  nl_devmode_text:     ./localized_images/nl/devmode.bmp
  nl_remove_text:      ./localized_images/nl/remove.bmp
  nl_yuck_text:        ./localized_images/nl/yuck.bmp
  nl_insert_text:      ./localized_images/nl/insert.bmp

  da_model_text:       ./localized_images/da/model.bmp
  da_devmode_text:     ./localized_images/da/devmode.bmp
  da_remove_text:      ./localized_images/da/remove.bmp
  da_yuck_text:        ./localized_images/da/yuck.bmp
  da_insert_text:      ./localized_images/da/insert.bmp

  no_model_text:       ./localized_images/no/model.bmp
  no_devmode_text:     ./localized_images/no/devmode.bmp
  no_remove_text:      ./localized_images/no/remove.bmp
  no_yuck_text:        ./localized_images/no/yuck.bmp
  no_insert_text:      ./localized_images/no/insert.bmp

  sv_model_text:       ./localized_images/sv/model.bmp
  sv_devmode_text:     ./localized_images/sv/devmode.bmp
  sv_remove_text:      ./localized_images/sv/remove.bmp
  sv_yuck_text:        ./localized_images/sv/yuck.bmp
  sv_insert_text:      ./localized_images/sv/insert.bmp

  fi_model_text:       ./localized_images/fi/model.bmp
  fi_devmode_text:     ./localized_images/fi/devmode.bmp
  fi_remove_text:      ./localized_images/fi/remove.bmp
  fi_yuck_text:        ./localized_images/fi/yuck.bmp
  fi_insert_text:      ./localized_images/fi/insert.bmp

  et_model_text:       ./localized_images/et/model.bmp
  et_devmode_text:     ./localized_images/et/devmode.bmp
  et_remove_text:      ./localized_images/et/remove.bmp
  et_yuck_text:        ./localized_images/et/yuck.bmp
  et_insert_text:      ./localized_images/et/insert.bmp

  lv_model_text:       ./localized_images/lv/model.bmp
  lv_devmode_text:     ./localized_images/lv/devmode.bmp
  lv_remove_text:      ./localized_images/lv/remove.bmp
  lv_yuck_text:        ./localized_images/lv/yuck.bmp
  lv_insert_text:      ./localized_images/lv/insert.bmp

  lt_model_text:       ./localized_images/lt/model.bmp
  lt_devmode_text:     ./localized_images/lt/devmode.bmp
  lt_remove_text:      ./localized_images/lt/remove.bmp
  lt_yuck_text:        ./localized_images/lt/yuck.bmp
  lt_insert_text:      ./localized_images/lt/insert.bmp

  ru_model_text:       ./localized_images/ru/model.bmp
  ru_devmode_text:     ./localized_images/ru/devmode.bmp
  ru_remove_text:      ./localized_images/ru/remove.bmp
  ru_yuck_text:        ./localized_images/ru/yuck.bmp
  ru_insert_text:      ./localized_images/ru/insert.bmp

  pl_model_text:       ./localized_images/pl/model.bmp
  pl_devmode_text:     ./localized_images/pl/devmode.bmp
  pl_remove_text:      ./localized_images/pl/remove.bmp
  pl_yuck_text:        ./localized_images/pl/yuck.bmp
  pl_insert_text:      ./localized_images/pl/insert.bmp

  cs_model_text:       ./localized_images/cs/model.bmp
  cs_devmode_text:     ./localized_images/cs/devmode.bmp
  cs_remove_text:      ./localized_images/cs/remove.bmp
  cs_yuck_text:        ./localized_images/cs/yuck.bmp
  cs_insert_text:      ./localized_images/cs/insert.bmp

  sk_model_text:       ./localized_images/sk/model.bmp
  sk_devmode_text:     ./localized_images/sk/devmode.bmp
  sk_remove_text:      ./localized_images/sk/remove.bmp
  sk_yuck_text:        ./localized_images/sk/yuck.bmp
  sk_insert_text:      ./localized_images/sk/insert.bmp

  hu_model_text:       ./localized_images/hu/model.bmp
  hu_devmode_text:     ./localized_images/hu/devmode.bmp
  hu_remove_text:      ./localized_images/hu/remove.bmp
  hu_yuck_text:        ./localized_images/hu/yuck.bmp
  hu_insert_text:      ./localized_images/hu/insert.bmp

  sl_model_text:       ./localized_images/sl/model.bmp
  sl_devmode_text:     ./localized_images/sl/devmode.bmp
  sl_remove_text:      ./localized_images/sl/remove.bmp
  sl_yuck_text:        ./localized_images/sl/yuck.bmp
  sl_insert_text:      ./localized_images/sl/insert.bmp

  sr_model_text:       ./localized_images/sr/model.bmp
  sr_devmode_text:     ./localized_images/sr/devmode.bmp
  sr_remove_text:      ./localized_images/sr/remove.bmp
  sr_yuck_text:        ./localized_images/sr/yuck.bmp
  sr_insert_text:      ./localized_images/sr/insert.bmp

  hr_model_text:       ./localized_images/hr/model.bmp
  hr_devmode_text:     ./localized_images/hr/devmode.bmp
  hr_remove_text:      ./localized_images/hr/remove.bmp
  hr_yuck_text:        ./localized_images/hr/yuck.bmp
  hr_insert_text:      ./localized_images/hr/insert.bmp

  bg_model_text:       ./localized_images/bg/model.bmp
  bg_devmode_text:     ./localized_images/bg/devmode.bmp
  bg_remove_text:      ./localized_images/bg/remove.bmp
  bg_yuck_text:        ./localized_images/bg/yuck.bmp
  bg_insert_text:      ./localized_images/bg/insert.bmp

  ro_model_text:       ./localized_images/ro/model.bmp
  ro_devmode_text:     ./localized_images/ro/devmode.bmp
  ro_remove_text:      ./localized_images/ro/remove.bmp
  ro_yuck_text:        ./localized_images/ro/yuck.bmp
  ro_insert_text:      ./localized_images/ro/insert.bmp

  uk_model_text:       ./localized_images/uk/model.bmp
  uk_devmode_text:     ./localized_images/uk/devmode.bmp
  uk_remove_text:      ./localized_images/uk/remove.bmp
  uk_yuck_text:        ./localized_images/uk/yuck.bmp
  uk_insert_text:      ./localized_images/uk/insert.bmp

  tr_model_text:       ./localized_images/tr/model.bmp
  tr_devmode_text:     ./localized_images/tr/devmode.bmp
  tr_remove_text:      ./localized_images/tr/remove.bmp
  tr_yuck_text:        ./localized_images/tr/yuck.bmp
  tr_insert_text:      ./localized_images/tr/insert.bmp

  iw_model_text:       ./localized_images/iw/model.bmp
  iw_devmode_text:     ./localized_images/iw/devmode.bmp
  iw_remove_text:      ./localized_images/iw/remove.bmp
  iw_yuck_text:        ./localized_images/iw/yuck.bmp
  iw_insert_text:      ./localized_images/iw/insert.bmp

  ar_model_text:       ./localized_images/ar/model.bmp
  ar_devmode_text:     ./localized_images/ar/devmode.bmp
  ar_remove_text:      ./localized_images/ar/remove.bmp
  ar_yuck_text:        ./localized_images/ar/yuck.bmp
  ar_insert_text:      ./localized_images/ar/insert.bmp

  fa_model_text:       ./localized_images/fa/model.bmp
  fa_devmode_text:     ./localized_images/fa/devmode.bmp
  fa_remove_text:      ./localized_images/fa/remove.bmp
  fa_yuck_text:        ./localized_images/fa/yuck.bmp
  fa_insert_text:      ./localized_images/fa/insert.bmp

  hi_model_text:       ./localized_images/hi/model.bmp
  hi_devmode_text:     ./localized_images/hi/devmode.bmp
  hi_remove_text:      ./localized_images/hi/remove.bmp
  hi_yuck_text:        ./localized_images/hi/yuck.bmp
  hi_insert_text:      ./localized_images/hi/insert.bmp

  th_model_text:       ./localized_images/th/model.bmp
  th_devmode_text:     ./localized_images/th/devmode.bmp
  th_remove_text:      ./localized_images/th/remove.bmp
  th_yuck_text:        ./localized_images/th/yuck.bmp
  th_insert_text:      ./localized_images/th/insert.bmp

  vi_model_text:       ./localized_images/vi/model.bmp
  vi_devmode_text:     ./localized_images/vi/devmode.bmp
  vi_remove_text:      ./localized_images/vi/remove.bmp
  vi_yuck_text:        ./localized_images/vi/yuck.bmp
  vi_insert_text:      ./localized_images/vi/insert.bmp

  id_model_text:       ./localized_images/id/model.bmp
  id_devmode_text:     ./localized_images/id/devmode.bmp
  id_remove_text:      ./localized_images/id/remove.bmp
  id_yuck_text:        ./localized_images/id/yuck.bmp
  id_insert_text:      ./localized_images/id/insert.bmp

  fil_model_text:       ./localized_images/fil/model.bmp
  fil_devmode_text:     ./localized_images/fil/devmode.bmp
  fil_remove_text:      ./localized_images/fil/remove.bmp
  fil_yuck_text:        ./localized_images/fil/yuck.bmp
  fil_insert_text:      ./localized_images/fil/insert.bmp

  zh_CN_model_text:       ./localized_images/zh_CN/model.bmp
  zh_CN_devmode_text:     ./localized_images/zh_CN/devmode.bmp
  zh_CN_remove_text:      ./localized_images/zh_CN/remove.bmp
  zh_CN_yuck_text:        ./localized_images/zh_CN/yuck.bmp
  zh_CN_insert_text:      ./localized_images/zh_CN/insert.bmp

  zh_TW_model_text:       ./localized_images/zh_TW/model.bmp
  zh_TW_devmode_text:     ./localized_images/zh_TW/devmode.bmp
  zh_TW_remove_text:      ./localized_images/zh_TW/remove.bmp
  zh_TW_yuck_text:        ./localized_images/zh_TW/yuck.bmp
  zh_TW_insert_text:      ./localized_images/zh_TW/insert.bmp

  ko_model_text:       ./localized_images/ko/model.bmp
  ko_devmode_text:     ./localized_images/ko/devmode.bmp
  ko_remove_text:      ./localized_images/ko/remove.bmp
  ko_yuck_text:        ./localized_images/ko/yuck.bmp
  ko_insert_text:      ./localized_images/ko/insert.bmp

  ja_model_text:       ./localized_images/ja/model.bmp
  ja_devmode_text:     ./localized_images/ja/devmode.bmp
  ja_remove_text:      ./localized_images/ja/remove.bmp
  ja_yuck_text:        ./localized_images/ja/yuck.bmp
  ja_insert_text:      ./localized_images/ja/insert.bmp

screens:
  en_devel:
    - [  0,   0, devmode_bg]
